---
name: WWW-Pastebin-UbuntuNlOrg-Retrieve
version: 0.001
author:
  - 'Zoffix <zoffix@cpan.org>'
abstract: retrieve pastes from http://paste.ubuntu-nl.org/ website
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  URI: 1.35
  WWW::Pastebin::Base::Retrieve: 0.001
build_requires:
  Test::More: 0
provides:
  WWW::Pastebin::UbuntuNlOrg::Retrieve:
    file: lib/WWW/Pastebin/UbuntuNlOrg/Retrieve.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
